### ISSUE TITLE
February 2024 site update compatibility

### ISSUE THREAD

**Issue by tompreuss** [tfedor/IsThereAnyDeal-Everywhere#12]
Looks like the recent site update has broken the extension.  The popup still appears on hover, but it's not finding the info or link to the correct page:

![image](https://github.com/IsThereAnyDeal/Everywhere/assets/1266699/0905ba6a-ffaa-4063-bd7c-268fbb371a24)

Not sure how much of a fix is necessary, I can see in my history the page used to be `https://isthereanydeal.com/game/baldursgateiii/history/` and now it's `https://isthereanydeal.com/game/baldurs-gate-3/history/` so it's using some kind of slightly different naming scheme.

**Comment by tfedor** [comment]
I will push a new version of extension within a week. Sorry for delay.

**Comment by tompreuss** [comment]
Oh no worries, and no rush! Just wanted to make sure you knew.  Thanks!

**Comment by tfedor** [comment]
New version has been posted, it's already up for Firefox, waiting for Chrome
