### ISSUE TITLE
Chrome extension no longer works

### ISSUE THREAD

**Issue by nielsbaan1992** [tfedor/IsThereAnyDeal-Everywhere#8]
![image](https://user-images.githubusercontent.com/37951470/119353314-071d8b80-bca3-11eb-8b02-06eb619a2ea6.png)
>⚠️ This extension has been disabled because it has been marked unsafe in the Chrome Web Store.

Also: the link for the corresponding extension is not reachable anymore:
https://chrome.google.com/webstore/detail/isthereanydeal-everywhere/fpkglohhcpgncijlhfnoloioahigjloj

**Comment by Jdewi12** [comment]
Works again for me

**Comment by nielsbaan1992** [comment]
Works for me too!
Thanks for the update, don't know if it's a Google thing or not, but anyway thanks!

**Comment by nielsbaan1992** [comment]
Yes, it works for me too, updated on Github, thanks for the update! 😊 Verzonden vanuit Mail voor Windows 10 Van: Jdewi12Verzonden: maandag 7 juni 2021 10:56Aan: tfedor/IsThereAnyDeal-EverywhereCC: nielsbaan1992; AuthorOnderwerp: Re: [tfedor/IsThereAnyDeal-Everywhere] Chrome extension no longer works (#8) Works again for me—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
